### ISSUE TITLE
Request URL too Long

### ISSUE THREAD

**Issue by Rojal123245** [pimcore/advanced-object-search#82]
After updating to latest pimcore I am getting Request too long error in Advanced object search.
![image](https://user-images.githubusercontent.com/25191918/73714318-a1696100-4738-11ea-9afe-12c809fe4d6a.png)

**Comment by Rojal123245** [comment]
will it be solved in next update. I need this bug to solved in our production pretty quickly.

**Comment by dvesh3** [comment]
@Rojal123245 you can provide a PR to change the method from GET to POST for grid proxy read api. We'll release next update as soon as we have the fix 😉

**Comment by Rojal123245** [comment]
in grid.js line no 139 pimcore set read to GET please change it To post thank you

**Comment by Rojal123245** [comment]
![image](https://user-images.githubusercontent.com/25191918/73833168-9e9e6700-4831-11ea-9c8d-52f361b2fbd8.png)
can this be the issue. @dvesh3

**Comment by dvesh3** [comment]
yes, it is related however the real cause is that whole gridconfig is passed in query param like when i selected country dropdown from gridconfig dialog
![image](https://user-images.githubusercontent.com/5137917/73834033-4a808c00-480b-11ea-8738-0a7865da92d7.png)
It generated request URI as it includes all fields config and maybe it is not required in the action so let's first see if can get rid of it otherwise we have to change read action method to POST in `resultpanel.js`
![image](https://user-images.githubusercontent.com/5137917/73834007-3b99d980-480b-11ea-8d72-08d440ee9d41.png)
